<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{2313c682-d879-48a2-96b0-58809e4ce1e8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	a:INT
	b:INT
	c:INT
	add1:FB_ADD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[add1(in1:=a, in2:=b, out=>c);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>